### ISSUE TITLE
add a build

### ISSUE THREAD

**Issue by Nacaroost** [Smux/dauntless-build-collection#68] opened 2019-12-28 14:50 UTC
when i want add a spesific build the site say " The provided url is not valid " but i go to dauntless collection buy dautless builder when i click on the dot in ritgh top and when u want  put another build its work but not for this build:
https://www.dauntless-builder.com/b/JwUwSoCxkH3Xh7FMUQTJTdTETmHmCRXCLTECd8SqZTACjRsOueCWPfLtNk

sorry if im not realy clear i'm french

**Comment by Nacaroost** [comment] 2019-12-31 09:06
i think i found the probleme because i do some test and all build i try to put on dauntless collection with a piece of malkarion can't be add

**Comment by Smux** [comment] 2020-01-22 13:12
@Nacaroost The issue is fixed now, there was an inconsistency in our data. You can try to maintain the build now :)

**Closed by Smux** 2020-01-22 13:12 UTC
